name: Build and Test

on:
  push:
    branches: [main]
    paths-ignore:
      #      - .github/**
      - Dockerfile
  pull_request:
    branches: [main]
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@main

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Set Node.js memory limits
        run: |
          echo "NODE_OPTIONS=--max-old-space-size=5096" >> $GITHUB_ENV
          echo "NPM_CONFIG_CACHE=/tmp/.npm" >> $GITHUB_ENV

      - name: Clean node_modules and lock (root)
        run: |
          rm -rf node_modules package-lock.json

      - name: Clean node_modules and lock (frontend)
        run: |
          rm -rf frontend/node_modules frontend/package-lock.json

      - name: Clean node_modules and lock (frontend/docs)
        run: |
          rm -rf frontend/docs/node_modules frontend/docs/package-lock.json

      - name: Install dependencies (root)
        run: npm install --no-optional --no-audit --no-fund

      - name: Install dependencies (frontend)
        run: cd frontend && npm install --no-optional --no-audit --no-fund

      - name: Install dependencies (frontend/docs)
        run: cd frontend/docs && npm install --no-optional --no-audit --no-fund

      - name: Test with memory optimization
        run: |
          npm install --save-dev ts-jest typescript
          npm test -- --detectOpenHandles --maxWorkers=2
          cd frontend
          npx vitest run --pool=forks --poolOptions.forks.singleFork=true

      - name: Build with retry mechanism
        run: |
          # 第一次尝试构建
          npm run build || (
            echo "第一次构建失败，清理缓存后重试..."
            rm -rf node_modules/.cache frontend/node_modules/.cache frontend/docs/node_modules/.cache
            npm run build
          ) || (
            echo "第二次构建失败，使用简化构建..."
            npm run build:simple
          ) || (
            echo "简化构建失败，使用最小构建..."
            npm run build:minimal
          )

      - name: Upload build artifacts
        uses: actions/upload-artifact@main
        with:
          name: build-artifacts
          path: |
            dist/
            frontend/dist/
            frontend/docs/build/
          retention-days: 30

      - name: Cache build artifacts
        uses: actions/cache@main
        with:
          path: |
            dist
            node_modules
            frontend/node_modules
            frontend/docs/node_modules
            /tmp/.npm
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-
