name: Build and Push Docker image

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'          # 忽略Markdown文件的更改
      - '**/.gitignore'     # 忽略.gitignore文件的更改
      - 'docs/**'           # 忽略docs目录下的所有更改
  pull_request:
    branches:
      - main               # 使工作流也响应针对main分支的Pull Request事件
     
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/docker-cache
          key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-    
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            happyclo/tts:latest
            happyclo/tts:${{ github.sha }}
          cache-from: type=local,src=/tmp/docker-cache
          cache-to: type=local,dest=/tmp/docker-cache,mode=max