name: Build and Test

on:
  push:
    branches: [main]
    paths-ignore:
      - .github/**
      - Dockerfile
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@main

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Generate package-lock.json
        run: npm install --package-lock-only

      - name: Install dependencies
        run: |
          npm install
          cd frontend
          npm install

      - name: Build
        run: npm run build

      - name: Cache build artifacts
        uses: actions/cache@main
        with:
          path: |
            dist
            node_modules
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-
