name: Fix Rollup Dependencies

on:
  workflow_dispatch:
  push:
    branches: [main, develop]
    paths:
      - "frontend/package.json"
      - "frontend/package-lock.json"

jobs:
  fix-rollup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Fix Rollup dependencies
        working-directory: ./frontend
        run: |
          echo "🔧 修复 Rollup 依赖问题..."

          # 删除 node_modules 和 package-lock.json
          rm -rf node_modules
          rm -f package-lock.json

          # 清理 npm 缓存
          npm cache clean --force

          # 重新安装依赖
          npm install

          # 验证构建
          npm run build:minimal

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add frontend/package-lock.json
          git commit -m "fix: update package-lock.json to resolve rollup dependencies" || exit 0
          git push
